name: Tests

on:
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Unit tests
        run: go test -race -timeout=1m ./...
